name: golangci-lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}

jobs:

  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
      checks: write

    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.26'
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: v2.10
